version: "3.9"
services:

  web-prod:
    image: "pysect-backend-notification-prod"
    container_name: pysect-backend-notification-prod
    #platform: linux/amd64
    build:
      target: builder_image
      context: .
      dockerfile: ./docker/express/Dockerfile
    networks:
      - nginx-reverse-proxy-net
    env_file:
      - ./docker/config/.env.prod
    environment:
      VIRTUAL_HOST: py.sect.letz.dev
      VIRTUAL_PATH: ~^/(api/notification)/
      VIRTUAL_PORT: 8000
    command: ./docker/express/local_run.sh

networks:
  nginx-reverse-proxy-net:
    external: true