version: "3.9"
services:

  web-local:
    image: "pysect-backend-notification-local"
    container_name: pysect-backend-notification-local
    ports:
      - "9003:8000"
    #platform: linux/amd64
    build:
      target: builder_image
      context: .
      dockerfile: ./docker/express/Dockerfile
    networks:
      - pysect-network
    env_file:
      - ./docker/config/.env
    command: ./docker/express/local_run.sh

networks:
  pysect-network:
    external: true