---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3.9"
services:

  web:
    image: "pysect-dev-backend-notification"
    container_name: pysect-dev-backend-notification
    ports:
      - "9003:8000"
    #platform: linux/amd64
    build:
      target: builder_image
      context: .
      dockerfile: ./docker/express/Dockerfile
    networks:
      - nginx-reverse-proxy-net
    env_file:
      - ./docker/config/.env
    environment:
      VIRTUAL_HOST: py.sect.test.letz.dev
      VIRTUAL_PATH: ~^/(api/notification)/
      VIRTUAL_PORT: 8000
    command: ./docker/express/local_run.sh

networks:
  nginx-reverse-proxy-net:
    external: true