# Use a specific version of Node.js.
FROM node:21 AS builder_image

# Set the working directory in the container.
WORKDIR /code

# Copy dependency manifests.
COPY package.json package-lock.json ./

# Install production dependencies.
RUN npm install

# Copy the rest of the application code.
COPY . .
